# Generated by Django 4.1.5 on 2023-01-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.AddField(
            model_name='product',
            name='caption',
            field=models.CharField(default='null', max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='null', max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.CharField(default='null', max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default='null', max_length=1000),
        ),
    ]
