# Generated by Django 4.1.2 on 2023-02-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_remove_product_detail_remove_product_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="caption",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="color",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.CharField(default="null", max_length=100),
        ),
    ]
