# Generated by Django 4.1.2 on 2023-02-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_product_caption_alter_product_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.FileField(
                blank=True,
                default="default_files/default_file.png",
                upload_to="account_files/images/",
            ),
        ),
    ]
