# Generated by Django 4.1.2 on 2023-02-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blog_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="tags",
            field=models.TextField(default="null"),
        ),
    ]
