# Generated by Django 4.1.2 on 2023-02-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="image",
            field=models.FileField(
                blank=True,
                default="default_files/default_file.png",
                upload_to="account_files/images/",
            ),
        ),
    ]
