# Generated by Django 4.1.5 on 2023-01-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='bio',
            new_name='business_type',
        ),
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='business',
            name='marketplace',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='business',
            name='marketplace_link',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='business',
            name='rc_number',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='business',
            name='website',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
