# Generated by Django 4.1.2 on 2023-02-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0002_rename_bio_business_business_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="promoted",
            field=models.BooleanField(default=False),
        ),
    ]
