# Generated by Django 4.1.2 on 2023-02-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0003_business_promoted"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="rating",
            field=models.CharField(default="0", max_length=10),
        ),
    ]
