# Generated by Django 4.1.2 on 2023-02-03 13:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0001_initial"),
        ("business", "0004_business_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="image",
            field=models.FileField(
                blank=True,
                default="default_files/default_file.png",
                upload_to="account_files/images/",
            ),
        ),
        migrations.CreateModel(
            name="BusinessReviewConnector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pub_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business.business",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="review.review"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="business",
            name="reviews",
            field=models.ManyToManyField(
                through="business.BusinessReviewConnector", to="review.review"
            ),
        ),
    ]
